---
title: Education
aliases: 
  - /education
toc: false
---
(The formal ones may be)

-   B.Tech in IT from [Netaji Subhash Engineering College](http://www.google.com/url?q=http%3A%2F%2Fnsec.ac.in&sa=D&sntz=1&usg=AFQjCNFe2EBGpA-oSLcYVmdISgkSmENcHg) (2013 - 17) (Final year dissertation: [A CFS–DNN-Based Intrusion Detection System](https://www.google.com/url?q=https%3A%2F%2Flink.springer.com%2Fchapter%2F10.1007%2F978-981-10-7901-6_19&sa=D&sntz=1&usg=AFQjCNG3tTcrgh7dSLAOYYjUY7PcCnpDQA))
-   High School from [Jadavpur Vidyapith](http://www.google.com/url?q=http%3A%2F%2Fjadavpurvidyapithhs.org%2F&sa=D&sntz=1&usg=AFQjCNEwgsSXPP9UKLU9PxZOHYFpMamXIA) (PCMC) (2005 - 13)
-   Courses/certifications relevant to my subject of interest:

    -   [Data Scientist with Python Track (DataCamp)](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fo1asim0it9204nv%2FData%2520Scientist%2520with%2520Python%2520Track.pdf%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNEFFOHFcOzP0mGWOxA6PbOxJkcDow)
    -   [Data Analyst with Python Track (DataCamp)](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fo1asim0it9204nv%2FData%2520Scientist%2520with%2520Python%2520Track.pdf%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNEFFOHFcOzP0mGWOxA6PbOxJkcDow)
    -   [Deep Learning Specialization (Coursera)](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fey8tl7ci24bc81r%2FDeep%2520Learning%2520Specialization%2520Coursera.pdf%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNHv5b59FKsX9LSt2m8s1U3lLJnchQ)
    -   [Advanced Machine Learning with TensorFlow on Google Cloud Platform (Coursera)](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fud6nuazsvcb4urt%2FAdvanced%2520Machine%2520Learning%2520with%2520TensorFlow%2520on%2520Google%2520Cloud%2520Platform.pdf%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNGVN8dCLRO7ug1CoiyHAC6xotLrbw)
    -   [TensorFlow in Practice Specialization (Coursera)](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fusd3e3lk7vo8fm1%2FTensorFlow%2520in%2520Practice%2520Specialization.pdf%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNEfC8RyLfHCsQEE2lZs1fg-uRfRxw)
    -   [TensorFlow: Data and Deployment Specialization (Coursera)](https://www.google.com/url?q=https%3A%2F%2Fwww.coursera.org%2Faccount%2Faccomplishments%2Fspecialization%2F7WB6WXTY53JD&sa=D&sntz=1&usg=AFQjCNFhgcNQVNegGBgdXsuCkuEKWJW7wQ)
    -   [Generative Adversarial Networks (GANs) (Coursera)](https://www.coursera.org/account/accomplishments/specialization/certificate/3U5QXRJXRVZC)
    -   [Natural Language Processing (Coursera)](https://www.coursera.org/account/accomplishments/specialization/certificate/FS7WK2VD2464)
    -   [TensorFlow Developer Certification](https://www.credential.net/76305e02-01c7-4240-9612-09143a17e3b8#gs.oxvgq4)
    -   [Mathematics for Machine Learning (Coursera)](https://www.coursera.org/account/accomplishments/specialization/certificate/ENKE8EHF4UUJ)
    -   [Machine Learning Engineering for Production (MLOps) (Coursera)](https://www.coursera.org/account/accomplishments/specialization/39NHJ9FGN3TF)
    -   [Professional Machine Learning Engineer (Google Cloud)](https://www.credential.net/dfb08300-0d91-4866-9409-908de346e658#gs.wchgzh)
