---
title: Interviews
aliases: 
  - /interviews
toc: false
---

The purpose of conducting these interviews is to mainly **get insights about the real-world project experiences, perspectives on learning new things**, some fun facts and thereby enriching the communities in the process. I sincerely thank the interviewees for taking the time out from their busy schedules and for agreeing to do these interviews. Here are the interviews I have done so far -

-   [An interview with **Robert Crowe**, Developer Advocate (TensorFlow) at Google](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-robert-crowe-developer-advocate-tensorflow-at-google-2a577056d005&sa=D&sntz=1&usg=AFQjCNGeAhL_hwGmeoQfxu-LX3xA8NCkEQ)
-   [An interview with **Snehasis Banerjee**, Scientist at TCS Research and Innovation](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-snehasis-banerjee-scientist-at-tcs-research-and-innovation-804a4cb52cb9&sa=D&sntz=1&usg=AFQjCNGbIgq6idzBUofOCnQuQKPRmUKDNw)
-   [An interview with **Abhishek Kumar**, Senior Manager, Data Science at Publicis Sapient](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-abhishek-kumar-senior-manager-data-science-at-publicis-sapient-fb29e0d25cf7&sa=D&sntz=1&usg=AFQjCNFg9nI6LMRes5HJNCxZ0irqzi4zUA)
-   [An interview with **Laurence Moroney**, Developer Advocate at Google](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-laurence-moroney-developer-advocate-at-google-5c0cd03a4033&sa=D&sntz=1&usg=AFQjCNEiYiKa86ek2DgA7ID5zyrE1QWzGg)
-   [An interview with **Karl Fezer**, AI Ecosystem Evangelist at Arm](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-karl-fezer-ai-ecosystem-evangelist-at-arm-a51436e53b0a&sa=D&sntz=1&usg=AFQjCNH00zalf5dKY_8Ubni1iQRr3N9m4w)
-   [An interview with **Dan Becker**, Team Lead of Kaggle Learn & Product Lead of Kaggle Kernels](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-dan-becker-team-lead-of-kaggle-learn-product-lead-of-kaggle-kernels-b27add8e914a&sa=D&sntz=1&usg=AFQjCNGDa6uSyTVayPhwckJNCdSEENlbPA)
-   [An interview with **Rajarshee Mitra**, Data Scientist at Microsoft](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-rajarshee-mitra-data-scientist-at-microsoft-fcbb9015b2d3&sa=D&sntz=1&usg=AFQjCNH4w0GcDpfaTWBG2jTd4hidzv74Cg)
-   [An interview with **Alessio**, Lead Data Scientist at FloydHub](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-alessio-lead-data-scientist-at-floydhub-8efd73c1b2b1&sa=D&sntz=1&usg=AFQjCNH7lGBAY1NRnlV3bP8Njh5skfsd6Q)
-   [An interview with **Joel Grus**, Research Engineer at Allen Institute for Artificial Intelligence](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-joel-grus-research-engineer-at-allen-institute-for-artificial-intelligence-e5c4b3a74aba&sa=D&sntz=1&usg=AFQjCNHwbhQEp31i3icEOF50BCWTCtoSsg)
-   [An interview with **Josh Tobin**, Research Scientist at OpenAI](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-josh-tobin-research-scientist-at-openai-f30305c20493&sa=D&sntz=1&usg=AFQjCNHBItLEv3eAlrbML5YXgKAXNT3uYQ)
-   [An interview with **Andrew Ferlitsch**, Developer Program Engineer at Google](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-andrew-ferlitsch-developer-program-engineer-at-google-d45d531f448a&sa=D&sntz=1&usg=AFQjCNHZ3HXcfrC2rtv9mT_zGfRLiyfFzA)
-   [An interview with **Shalini De Mello**, Principal Research Scientist at NVIDIA](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2F2LQMA8I&sa=D&sntz=1&usg=AFQjCNFpUiMyeKeNPpzdhMO0nj-a25RmzA)
-   [An interview with **Rahul Agrawal**, Principal Machine Learning Manager at AI and Research, Microsoft](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2F2VwuY5d&sa=D&sntz=1&usg=AFQjCNG_INeHSutK-b6GAqvqx3_VoxhL9g)
-   [An interview with **Aakash Nain**, Research Engineer at Ola](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2F35x24X5&sa=D&sntz=1&usg=AFQjCNFb3IbuO--gms8-qJ2O8BHFOimszQ)
-   [An interview with **Xander Steenbrugge**, Machine Learning Researcher & YouTuber at “Arxiv Insights”](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-xander-steenbrugge-machine-learning-researcher-youtuber-at-arxiv-insights-696d8f62ceb5&sa=D&sntz=1&usg=AFQjCNHMIVJODJokbxXtlyp08wy4im6Nkw)
-   [An interview with **Ines Montani**, Co-founder at Explosion](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-ines-montani-co-founder-at-explosion-114afef7b48a&sa=D&sntz=1&usg=AFQjCNHU8-t0_fNXMc9mmI_4oyMBmBJMTA)
-   [An interview with **Girish Palshikar**, Principal Scientist at TCS Research and Innovation](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-girish-palshikar-principal-scientist-at-tcs-research-and-innovation-5dc257356f5a&sa=D&sntz=1&usg=AFQjCNF8fl8zS8c7mdSmKNqwNoaxMlx9zQ)
-   [An interview with **Christoph Molnar**, Interpretable Machine Learning Researcher](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-christoph-molnar-interpretable-machine-learning-researcher-7c133c73d5c5&sa=D&sntz=1&usg=AFQjCNFlHWxeggE5RVZzo3FY0gD4a5teIA)
-   [An interview with **Leslie Smith**, Senior Research Scientist at U.S. Naval Research Laboratory](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-leslie-smith-senior-research-scientist-at-u-s-naval-research-laboratory-6ed64868f893&sa=D&sntz=1&usg=AFQjCNEBGMd1IAA0S2Gi3GnXa6eOgDraoQ)
-   [An interview with **Arindam Pal**, Senior Research Scientist at CSIRO](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-arindam-pal-senior-research-scientist-at-csiro-afb27e230453&sa=D&sntz=1&usg=AFQjCNFG8ii77_bc9XOP2sS50X7A_20R0g)
-   [An interview with **Ankur Patel**, Vice President of Data Science at 7Park Data](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-ankur-patel-vice-president-of-data-science-at-7park-data-bdabbb97be33&sa=D&sntz=1&usg=AFQjCNE4U8gJSOZfyL5Ho6A9eNPeqyIRAA)
-   [An interview with **Max Pumperla**, Deep Learning Engineer at Skymind](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-max-pumperla-deep-learning-engineer-at-skymind-a404afda1afa&sa=D&sntz=1&usg=AFQjCNHFq8jkMasuPLlELD3heDQ5INrYlg)
-   [An interview with **Abhishek Thakur**, Data Scientist, and Kaggle 3x Grandmaster](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-abhishek-thakur-data-scientist-and-kaggle-3x-grandmaster-47605c95ab0&sa=D&sntz=1&usg=AFQjCNH0fjCKsUpcpA3am-WFCSrXUcrrlA)
-   [An interview with **Dmytro Mishkin**, Computer Vision Researcher](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-dmytro-mishkin-computer-vision-researcher-7d6ba60a14c1&sa=D&sntz=1&usg=AFQjCNH9VKr0JknknXcWjk6sApBWZYgiVQ)
-   [An interview with **Ellick Chan**, Head of University Relations and Research — Intel AI Academy](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-ellick-chan-head-of-university-relations-and-research-intel-ai-academy-67d366dc5661&sa=D&sntz=1&usg=AFQjCNEB8CePyPYSfItN4c4blzsMYbMyYQ)
-   [An interview with **Thomas Wolf**, Chief Science Officer at Hugging Face](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-thomas-wolf-chief-science-officer-at-hugging-face-ee585f782997&sa=D&sntz=1&usg=AFQjCNHdDdMNYdU5y9L4ZuNiFizTve-u2A)
-   [An interview with **Dat Tran**, Head of AI at Axel Springer AI](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-dat-tran-head-of-ai-at-axel-springer-ai-11c6bcc700e3&sa=D&sntz=1&usg=AFQjCNEBKKkPbF4P2s_PNZrDJj6hnR3QMA)
-   [An interview with **Daniel Seita**, Ph.D. student at UC, Berkeley](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-daniel-seita-ph-d-student-at-uc-berkeley-715e739b2bc3&sa=D&sntz=1&usg=AFQjCNHckTLo7Mrn1fMOcXEJmIThoU0j8w)
-   [An interview with **Vladimir Iglovikov**, Senior Computer Vision Engineer at Lyft](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-vladimir-iglovikov-senior-computer-vision-engineer-at-lyft-f511842a6b9b&sa=D&sntz=1&usg=AFQjCNHfK698EUGhBw340fhMNQM2wA7v3Q)
-   [An interview with **Hamel Husain**, Staff Machine Learning Engineer at GitHub](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40spsayakpaul%2Fan-interview-with-hamel-husain-staff-machine-learning-engineer-at-github-a39c21af0414&sa=D&sntz=1&usg=AFQjCNEgXagB1brKICBUei_ajOziq264Lw)
-   [An interview with **Patrick Hall**, Principal Scientist at bnh.ai and Advisor to H2O.ai](https://medium.com/@spsayakpaul/an-interview-with-patrick-hall-principal-scientist-at-bnh-ai-and-advisor-to-h2o-ai-74631d58a660)
-   [An interview with **Colin Raffel**, Research Scientist at Google](https://medium.com/@spsayakpaul/an-interview-with-colin-raffel-research-scientist-at-google-5e445a5e57c6)
-   [An interview with **Niki Parmar**, Senior Research Scientist at Google Brain](https://medium.com/@spsayakpaul/an-interview-with-niki-parmar-senior-research-scientist-at-google-brain-74a592596cb3)
-   [An interview with **Alexander (Sasha) Rush**, Associate Professor at Cornell University](https://medium.com/@spsayakpaul/an-interview-with-alexander-sasha-rush-associate-professor-at-cornell-university-220fed1e87ea)
-   [An interview with **Vincent Sitzmann**, Postdoctoral Researcher at MIT](https://medium.com/@spsayakpaul/an-interview-with-vincent-sitzmann-postdoctoral-researcher-at-mit-46edbd72aa84)
-   [An interview with **Dan Hendrycks**, Ph.D. student at UC Berkeley](https://medium.com/@spsayakpaul/an-interview-with-dan-hendrycks-ph-d-student-at-uc-berkeley-c546e7c76657)

I have had an amazing time interviewing these incredible folks and I am grateful to them. For other competing priorities, I am discontinuing the series for an indefinite period. If you enjoy reading through interviews like these, you might want to check out the [**Machine Learning Street Talk**](https://www.youtube.com/channel/UCMLtBahI5DMrt0NPvDSoIRQ) podcast on YouTube.  
