---
title: "Talks/Seminars/Workshops"
aliases: 
  - /talksseminarsworkshops
toc: false
---
I love to attend developer meetups, conferences, workshops and learn from them as much as I can. I sometimes talk on a range of topics that I love the most. All the slides of my talks/sessions can be found below.

### Given by me

-   Presented our paper  [**A CFS–DNN-Based Intrusion Detection System**](https://www.google.com/url?q=https%3A%2F%2Fdoi.org%2F10.1007%2F978-981-10-7901-6_19&sa=D&sntz=1&usg=AFQjCNFzOUPqdOOKBps043v56wGUSi5N1g)  at  [International Conference on Communication Devices and Networking](https://www.google.com/url?q=https%3A%2F%2Fwww.springer.com%2Fin%2Fbook%2F9789811079009&sa=D&sntz=1&usg=AFQjCNH9Jj9pNtHNGg70klxFjcGHRSjc7g), Sikkim Manipal Institute of Technology, Sikkim, June 3, 2017.
-   Presented our paper  [**A Comparative Study of Different Ensemble Learning Techniques Using Wisconsin Breast Cancer Dataset**,](https://www.google.com/url?q=https%3A%2F%2Fieeexplore.ieee.org%2Fdocument%2F8526215&sa=D&sntz=1&usg=AFQjCNFdSr2phgcOOtf9-V7NPeANKmfE5g)  at  [International Conference on Computer, Electrical & Communication Engineering](http://www.google.com/url?q=http%3A%2F%2Ficcece.com%2Ficcece17%2Findex.php&sa=D&sntz=1&usg=AFQjCNG3jUTAcwuFzzrSIQfs3bYsvaSX6w), Techno India University, Kolkata, December 23, 2017.
-   Co-presented our paper  [**A Novel Transfer Learning-Based Missing Value Imputation on Discipline Diverse Real Test Datasets—A Comparative Study with Different Machine Learning Algorithms**](https://www.google.com/url?q=https%3A%2F%2Flink.springer.com%2Fchapter%2F10.1007%252F978-981-13-1501-5_71&sa=D&sntz=1&usg=AFQjCNEbP-XwVNxKc3u9OvrY2_UzHJtOCQ)  at  [International Conference on Emerging Technologies in Data Mining and Information Security](http://www.google.com/url?q=http%3A%2F%2Fiem.edu.in%2Finternational-conference-emerging-technologies-data-mining-information-security-iemis-2018%2F&sa=D&sntz=1&usg=AFQjCNFFSWnWYwPw0_PXqXl91ti0x2lvQA), University of Engineering and Management, Kolkata, February 23, 2018.
-   Spoke on  [**Cyclical Learning Rates for training Neural Nets**](https://drive.google.com/file/d/1mF7Nj2DZeYDf5zSeja-kCsqXLyy6vNVg/view?usp=sharing)  at  [DevFest Kolkata](https://www.google.com/url?q=https%3A%2F%2Fdevfest18.gdgkolkata.org%2F&sa=D&sntz=1&usg=AFQjCNEjjoEDeVjmTZ-1VKeubDqEAUN-NA), November 3, 2018.
-   Conducted a hack-session on  **Cyclical Learning Rates**  at  [DataHack Summit (organized by Analytics Vidhya)](https://www.google.com/url?q=https%3A%2F%2Fwww.analyticsvidhya.com%2Fdatahack-summit-2018%2Fsessions%2Fperforming-unsupervised-neural-machine-translation-to-and-from-rare-languages%2F&sa=D&sntz=1&usg=AFQjCNHPlGwqfTq3ipbhAl8UNaarocDI1w), Bangalore, November 23, 2018.
-   Delivered talks on  [**Introduction to BigQuery**](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fsayakpaul%2FTalksGiven%2Fblob%2Fmaster%2FBigQuery%2520presentation%2520deck%2520-%2520Sayak.pdf&sa=D&sntz=1&usg=AFQjCNELNO2GIs-FeRXhuCvGRygWwZ1VNA)  at  [**GDG Kolkata Cloud Study Jam (Academy of Technology)**](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F260376495%2F&sa=D&sntz=1&usg=AFQjCNGAV40hRhbVhk3THg5bUH5WyZ6kSw), **[Google Cloud Next '19 Extended - Kolkata](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F260592925%2F&sa=D&sntz=1&usg=AFQjCNEH4KUfKsHnmXrFf4sAOmz3zGLS-w)** on April 12 and April 19, 2019 respectively.
-   Conducted a session on  [**Ten Updates Introduced in TensorFlow 2.0**](https://www.google.com/url?q=https%3A%2F%2Fwww.datacamp.com%2Fcommunity%2Ftutorials%2Ften-important-updates-tensorflow&sa=D&sntz=1&usg=AFQjCNFoU7o7uLhytdbXJfbYat7hBWTPvA)  along with a short quiz at  [Google I/O Extended 2019, Kolkata](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F261068613%2F&sa=D&sntz=1&usg=AFQjCNFVgksGT5O5g1crBtzY4yVwzL7ytA), May 11, 2019.
-   Conducted a session on **[Training neural nets: A methodical approach](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fsayakpaul%2FTalksGiven%2Fblob%2Fmaster%2FML_AR%2520Developer%2520Day%2520Deck%2520-%2520Sayak.pdf&sa=D&sntz=1&usg=AFQjCNHmnFHVFo86s0C2NUgJmmlYqBOaTA)** at  [**ML/AR Developer Day**](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F261645026%2F&sa=D&sntz=1&usg=AFQjCNHMSl--jsZZw7jQIjZoiCEBaulDRA)  organized by  [GDG Kolkata](http://www.google.com/url?q=http%3A%2F%2Fgdgkolkata.org&sa=D&sntz=1&usg=AFQjCNG87VdFugK0x5psF2P7cuEwne4DXQ)  and  [DSC HIT](https://www.google.com/url?q=https%3A%2F%2Fmedium.com%2F%40dscheritageit&sa=D&sntz=1&usg=AFQjCNG9Dirn3xWQLh7QMsGvNh91eeiEhA)  (May 30, 2019)**.**
    -   Conducted the same session but in a more detailed manner at  [**ML With The Experts - GDG Kolkata Meetup**](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F262780353%2F&sa=D&sntz=1&usg=AFQjCNG4QPJV9V6J0GoeXxpc-RT7rjbZ4w)  (July 7, 2019).
-   Spoke at  [Google I/O Extended 2019, Bhubaneswar](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Bhubaneswar%2Fevents%2F260798274%2F&sa=D&sntz=1&usg=AFQjCNHxBHN9WfxO61OEleHuINkQ2hqOew)  on  [**Ten Updates Introduced in TensorFlow 2.0**](https://www.google.com/url?q=https%3A%2F%2Fwww.datacamp.com%2Fcommunity%2Ftutorials%2Ften-important-updates-tensorflow&sa=D&sntz=1&usg=AFQjCNFoU7o7uLhytdbXJfbYat7hBWTPvA)**,** June 9, 2019. Also shared a few opportunities with the students ([link](https://docs.google.com/presentation/d/1L_IRyRhJTKfd99biqOSxQI6j9i_swjx1M_x1Nkd4zzQ/edit?usp=sharing)  to the  **Opportunities'** deck).
-   Spoke at  [DevFest Kolkata 2019](http://www.google.com/url?q=http%3A%2F%2Fdevfest.gdgkolkata.org%2Fspeakers&sa=D&sntz=1&usg=AFQjCNF56yMUd8h3SEIHGsVzVi_NEZfR2A)  about  _how to approach the process of model deployment_, August 3, 2019_._ My talk was titled  **Connecting Flutter with TensorFlow 2.0**. Link to the  [slides](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fsayakpaul%2FTalksGiven%2Fblob%2Fmaster%2FDevFest%2520Kolkata%25202019%2520Deck%2520-%2520Pawan%2520and%2520Sayak.pdf&sa=D&sntz=1&usg=AFQjCNGpofn6n9PgSwV6pzXDVDWCUO2i8w),  [video](https://youtu.be/gpNVoXVWIq8)  and the  [GitHub repository](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fsayakpaul%2FGDE-Collaboration&sa=D&sntz=1&usg=AFQjCNGxAl0TdAu0y22Sa3UZXT0r69fuyA).
-   Spoke at  [DevFest Jaipur 2019](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Jaipur%2Fevents%2F263590039%2F&sa=D&sntz=1&usg=AFQjCNFNB3HJUr3483pvL-rdpCZmAP2eWw)  (September 08, 2019) on  [**Structuring Machine Learning Projects**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FJaipur19&sa=D&sntz=1&usg=AFQjCNH7rg2VdYAXypTvfBBQbBdUYLlWNg).
    -   Remotely presented on this topic at  [DevFest Izmir 2019](https://www.google.com/url?q=https%3A%2F%2Fgdgizmir.org%2F&sa=D&sntz=1&usg=AFQjCNHSvNI9t7QRNaEm3SDentHew_VJcQ)  (November 23, 2019). Here's the  [modified deck](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fizmir-sayak&sa=D&sntz=1&usg=AFQjCNHadWBk-TijFNPNotgZwOICHte8dg). [Here's](https://www.youtube.com/watch?v=3_-zToE0tsw) a recording of the session. 
-   Spoke at  [Explore ML Academy](https://events.withgoogle.com/explore-ml-in/)  on  [**Problem Framing**](https://docs.google.com/presentation/d/1p6WCeQgIMJDVLd6Fw1Nlmyy9wC5ic1Z-6voCQi8q5WM/edit?usp=sharing)  and  [**How to find data set and fairness practices**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FExploreML19&sa=D&sntz=1&usg=AFQjCNFnbxLqwf9e9beLJUqv_Lou9u05dQ)**,**  September 14, 2019, Hyderabad.
-   Spoke at  [DevFest Bhubaneswar 2019](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Bhubaneswar%2Fevents%2F262747492%2F&sa=D&sntz=1&usg=AFQjCNEaICNpHmVB6JfZHEUbMojV3IGsgA)  (September 22, 2019) on  [**The Human Loop in Machine Learning**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FBBSR19&sa=D&sntz=1&usg=AFQjCNExItQErAFMR5SvLHBUQeCP9KXUMw).
-   Spoke at  [DevFest Goa 2019](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGoogleGoa%2Fevents%2F264790819%2F&sa=D&sntz=1&usg=AFQjCNElnS4-StCOyn34Ju5C8RfbcVVxyg)  (September 29, 2019) on **[Training Neural Nets: a Hacker's Perspective](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FDFGoa19&sa=D&sntz=1&usg=AFQjCNFCgTmx2gx6ilK4BrccF7JOLlDpzg)**.
    -   Spoke at  [**Class III of Launchpad Accelerator India**](https://india.googleblog.com/2019/08/inviting-applications-for-class-3-of.html)  (October 16, 2019), Bangalore on an extended version of the same topic. Deck:  [http://bit.ly/LPA_3](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FLPA_3&sa=D&sntz=1&usg=AFQjCNFOFlrXqeRhiZ-ohJMkQNpkNydzmA).
    -   Remotely presented on this topic at  [DevFest Warsaw & Radzymin 2019](https://www.google.com/url?q=https%3A%2F%2Fwarrad.devfest.pl%2F&sa=D&sntz=1&usg=AFQjCNEtza6n4fZHJHp5nlw6hLXlqByWbg)  (December 7, 2019).
-   Presented my work on  [**Blood Cell Detection using TensorFlow Object Detection API**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FBloodCell&sa=D&sntz=1&usg=AFQjCNEjLeZnlTf6qPeMEtyIrIfkqWkq3w)  at  [TensorFlow Roadshow, Bangalore](https://events.withgoogle.com/tensorflow-roadshow-bengaluru/)  (October 01, 2019). Deck:  [http://bit.ly/tf-roadshow-sayak](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Ftf-roadshow-sayak&sa=D&sntz=1&usg=AFQjCNH00PRCN-Ccb76fwuSkdBGBTooEEA).
-   Remotely presented my work on  [**Predicting Publisher's Names from Hackernews Article Titles**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2F2K9TpS8&sa=D&sntz=1&usg=AFQjCNHYVn1jY9D0pTkUkMCPGVup-5y-Sw)  at Global GDE Summit (October 26, 2019). Video available  [here](https://drive.google.com/file/d/1-2ffOTomvKN01gdy6SS1Uy2bWKphcfZp/view?usp=sharing)  (Courtesy:  [Akshay Bahadur](https://www.google.com/url?q=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fakshaybahadur21%2F&sa=D&sntz=1&usg=AFQjCNFISgFoKfYfmo3LHMy1fFE_Ga72kg)). Deck:  [http://bit.ly/GDESummit19](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FGDESummit19&sa=D&sntz=1&usg=AFQjCNFKyNWyBm-u9H3fDmFew0x6KZ4pzA).
-   Remotely presented at  [Machine Learning Weekend](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Fhashtag%2FMachineLearningWeekend%3Fsrc%3Dhashtag_click&sa=D&sntz=1&usg=AFQjCNFqplz1ecCmRFFW9tmHZzvOzj_Y6Q), Turkey on  [**Building data pipelines with tf.data**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2FMLWeekend19&sa=D&sntz=1&usg=AFQjCNGPsKXGfxbZDLWgudr2S5vdb2FGZQ)  (November 3, 2019).
-   Presented at  [Kaggle Days Mumbai](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FKaggle-Days-Meetup-Mumbai%2F&sa=D&sntz=1&usg=AFQjCNFiWV5th2OxJQtrzNXUD_JYi9arpw)  on  [**On the learning dynamics of neural nets**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fkaggle-days-sayak&sa=D&sntz=1&usg=AFQjCNF-y7p9ec-00H6vXPoqK5qr1hwUXA)  (November 30, 2019).
-   Conducted a workshop on  **Applied Deep Learning using TensorFlow 2.0 and GCP**  (includes topics like  _data pipeline optimization_,  _cyclical learning rates_,  _mixed-precision training_  and so on) at  **Launchpad India Accelerator Bootcamp**  (December 12 - 13, 2019). Content available here:  [http://bit.ly/mlb-code-sayak](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fmlb-code-sayak&sa=D&sntz=1&usg=AFQjCNGZ3dKzVt8cxekrKL69HqS5iOG9JA).
-   Spoke at  [DevLoop](https://www.google.com/url?q=https%3A%2F%2Fmehdev.club%2Fdevloop%2F&sa=D&sntz=1&usg=AFQjCNFYHjl8_viI4U5xbFyQFdipy1kPhQ)  on  **Your first machine learning project**, Ganpat University, Gujrat, India (January 04, 2020). Deck:  [http://bit.ly/dloop20](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fdloop20&sa=D&sntz=1&usg=AFQjCNFhcTAl4keytjKkZ6-9dOyTpLo9qQ). I have spoken about this topic at multiple occasions. A session recording is available [here](https://youtu.be/dllfKQKlzvg).
-   Spoke at  [Improving machine learning model](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDGBangalore%2Fevents%2F268346705%2F&sa=D&sntz=1&usg=AFQjCNG8jyuu1e_8TQj9olOmybCQG1uS7g)  on  **Weights and Biases for better machine learning**, Bangalore (February 08, 2020). Deck:  [http://bit.ly/blr-wb](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fblr-wb&sa=D&sntz=1&usg=AFQjCNHsyPW6oPsLBgLaxcq83G57jXNxRQ).
-   Spoke at  [Sigma 2020](https://www.google.com/url?q=https%3A%2F%2Fallevents.in%2Fkolkata%2Fsigma-2020-a-transit-through-time%2F200018965165649&sa=D&sntz=1&usg=AFQjCNEGZzZ3zJWPG1Gc0Isu_lImfO4lng)  on  [**Machine Learning: For the Community by the Community**](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fsigma-2020&sa=D&sntz=1&usg=AFQjCNE8blxrQUY7mdenSPAEodTvKjThxQ)**,** Kolkata (February 12, 2020).
-   Spoke at  [MENA Digital Days 2020](https://events.withgoogle.com/menadd/) on  **Building data pipelines with tf.data**. Deck  [here](https://www.google.com/url?q=https%3A%2F%2Fbit.ly%2Fmena-20&sa=D&sntz=1&usg=AFQjCNEBpjCupJ7v_Yogqwwf6o5otxB2Bg), session video  [here](https://www.youtube.com/watch?v=fc0_eLmxm0E&feature=em-lbrm).
-   Spoke for GDG Goa at an  [online event](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGoogleGoa%2Fevents%2F269678892%2F&sa=D&sntz=1&usg=AFQjCNGqyk2Nz7e4JTBM9_e016tdBRfGPw)  on  **Hello, TensorFlow**. Deck  [here](http://www.google.com/url?q=http%3A%2F%2Fbit.ly%2Fgdg-goa-20&sa=D&sntz=1&usg=AFQjCNFCE4R-fZwB2SraKegXfxSMhfhd2Q), session  [here](https://www.youtube.com/watch?v=z_S8hCOxLWo).
-   Spoke for GDG Pune and WTM Pune on [**Doing more with TensorFlow Lite**](https://bit.ly/tfl-pune), April 26, 2020. A session recording is available [here](https://youtu.be/U-8YeVpevdc) (it was for the Deep Learning Salon hosted by Weights and Biases). 
- Spoke for Global AI Hub, Turkey on [**Gotchas of Transfer Learning for Image Classification**](http://bit.ly/tl-sayak), May 01, 2020. A recording of the session is available [here](https://www.youtube.com/watch?v=nSMZ3GPZPX0). 
- Spoke on **TensorFlow Hub: Models, Models, and Models** for [TFUG Hyderabad](https://twitter.com/tfughyd/status/1255503396108410880) on May 03, 2020. Deck: [http://bit.ly/tf-hub](http://bit.ly/tf-hub). A recording of the session is available [here](https://www.youtube.com/watch?v=jVNZd3KA2FI). 
-   Participated in an ML fire-side chat hosted by [Aniedi](https://twitter.com/aniediudo) to speak to the developers of African regions. Recording is available [here](https://www.youtube.com/watch?v=y1mwuxWvd8w) (May 30, 2020). 
-   Spoke at Pie and AI Kolkata on **Becoming One with the Data**. Deck [here](https://bit.ly/one-data) & session recording [here](https://bit.ly/dlailive) (May 31, 2020).
-   Spoke on **Model Optimization 101** for [TFUG Thrissur](https://www.meetup.com/tfug-thrissur/photos/30888563/490730360/). Deck [here](http://bit.ly/mo-101) (June 07, 2020). A recording on the same topic from a different event is available [here](https://youtu.be/u5_JorytAcI). I have also presented this at Google for Startups Accelerator India ([GoogleDevsIN tweet](https://twitter.com/GoogleDevsIN/status/1302932126019411970)). A recording of that session is available [here](https://youtu.be/plSkz8Eqnlo). 
-   Spoke on **A few good stuff in TensorFlow Lite** for [GDG Berlin](https://www.meetup.com/gdg-berlin/events/271458374/) (July 16, 2020). Deck is available [here](http://bit.ly/stuff-tflite) and a recording is available [here](https://www.youtube.com/watch?v=Ly4s0fsG93c). 
-   Spoke on **GitHub Actions for Machine Learning** at Global AI On Tour Mumbai (September 27, 2020). Deck is available [here](http://bit.ly/ga-ml).
-   Spoke on **The Maker Philosophy with ML APIs** at [Mindhack Summit](https://www.mindhacksummit.com/) (October 12, 2020). Deck is available [here](https://bit.ly/maker-api). 
-   Spoke on **Adversarial Examples in Deep Learning** at [DevFest UK & Ireland 2020](https://www.devfest-uki.com/speakers-more-details) (October 17, 2020). Deck is available [here](http://bit.ly/ia-101).
-   Took a workshop on **Adversarial Robustness in Deep Learning** with [Dipanjan Sarkar](https://www.linkedin.com/in/dipanzan/) at [Deep Learning DevCon 2020](https://dldc.adasci.org/) (October 29, 2020). The materials are available here - [bit.ly/adv_learn](http://bit.ly/adv_learn). We presented this at Kshitij 2021 as well and [here's the recording](https://youtu.be/RV7nerh_8gw). 
-   Spoke on **Demystifying Self-Supervised Learning for Visual Recognition** at [SciPy Japan 2020](https://www.scipyjapan.scipy.org/schedule) (October 30, 2020). Deck is available here - [bit.ly/scipy-sp](http://bit.ly/scipy-sp). Session recording is available [here](https://www.youtube.com/watch?v=3686AJmoDTA).
-   Spoke to Santosh on **Demystifying ML and AI for beginners** at his podcast [Tech Talks With Santosh](https://www.youtube.com/channel/UChvYTafHRgXKb0VbYGeG0nw): [https://youtu.be/BhLQN-XIO04](https://youtu.be/BhLQN-XIO04) (November 07, 2020). 
- Spoke on **Key Trends of Computer Vision 2021** (June 09, 2021). Deck is available [here](http://bit.ly/trends-cv). A session recording is available
  [here](https://www.youtube.com/watch?v=KQFJRZgNrDA). A blog post summarizing the content (by Benedict Neo) is available [here](https://medium.com/bitgrit-data-science-publication/5-computer-vision-trends-for-2021-96fd18d5596c). I have also presented this at [Takshak'21](https://takshak.roboism.in/robobuzz), Techfest of ISM Dhanbad.
- **Vertex AI for Easier Model Deployments** at [Google for Startups Accelerator Class 5](https://india.googleblog.com/2021/08/introducing-class-5-of-google-for.html) (August 28, 2021). Deck is available [here](https://bit.ly/gfsa-vertex). A recording is available [here](https://youtu.be/gzM0lJWtvic).
- **Enabling Possibilities with Open-Source in Machine Learning** at [DevFest India 2021](https://devfestindia.com/schedule/1012) (October 24, 2021). My deck is available [here](https://docs.google.com/presentation/d/1qXBqjSpNQFDxVAiuormJdDWph_YHs33BBxptsetoj74/edit?usp=sharing). A recording is available [here](https://youtu.be/VsBEFUoESR4?t=3123).
- **Citizen Scientists Tackling Devastating Floods and Disaster Relief with Semi-supervised Deep Learning** at [NVIDIA GTC 2021](https://events.rainfocus.com/widget/nvidia/nvidiagtc/scheduler/session/1630006454504001Z8CH) (November 09, 2021). This is based on [our work on
using semi-supervision for segmenting flood regions](https://arxiv.org/abs/2107.08369). This work was also presented as a poster at [PyTorch Developer
Day](https://docs.google.com/document/d/1oRkGg3kc99Ozcketdkpwub8BI26omKkb/edit#) and the PyTorch team helped us create a
[beautiful poster](https://drive.google.com/file/d/1FGf-Jz42kcicNmhoR1e26Z5MSicChrZr/view?usp=sharing) for that. 
- **Improving Dataflow pipelines for text data at scale** (with [Nilabhra Roy Chowdhury](https://www.linkedin.com/in/nilabhraroychowdhury)) at [Innovators Hive from Google Cloud](https://cloud.google.com/innovators/hive2022) (March 30, 2022). We also presented this at the [Beam Summit 2022](https://2022.beamsummit.org/sessions/improving-beam-dataflow-pipelines-for-text-data-processing/). Slide deck is available [here](https://docs.google.com/presentation/d/1EAn4_pNZzt0_8mz_VAuccSySU3DpNoYN5X04amvkbC0/edit?usp=sharing). A video presentation is available [here](https://youtu.be/dkR-Sl7WHq8).
- **Building a Mobile-optimized Image Recognition Model** at [DevFest Bangalore 2022](https://gdg.community.dev/events/details/google-gdg-bangalore-presents-devfest-bangalore-2022/) (September 18, 2022). Slides are [here](https://docs.google.com/presentation/d/120CeL_V5hcSSJv3Lktnh45H3XKlIu9LQ_jnAlTrah08/edit?usp=sharing). A recording is [here](https://youtu.be/OL1t7OlX3z4?t=5720).
- **Fantastic ML Deployments & How to do them with Vertex AI** at [Cloud Community Days Ahmedabad 2022](https://gdg.community.dev/events/details/google-gdg-cloud-ahmedabad-presents-google-cloud-community-day-ahmedabad-2022/) (September 24, 2022). Slides are [here](https://bit.ly/ccd-ahm-deck).
- **Better Hardware Provisioning for ML Experiments on GCP** at [Cloud Next 2022](https://inthecloud.withgoogle.com/bengaluru-innovators-hive-next-22-13oct/register.html) (October 13, 2022). All the materials are [here](https://github.com/carted/cloud-next-22-terraform). A video recording is available [here](https://youtu.be/Q6BqBlUN8Lc).
- **Being a Maker with ML APIs** at [DevFest Jalandhar 2022](https://gdg.community.dev/events/details/google-gdg-jalandhar-presents-devfest-jalandhar-2022/) (October 16, 2022). All the materials are [here](https://bit.ly/jal-22).
- **Anatomy of Capstone ML Projects** at [DevFest Nagpur 2022](https://gdg.community.dev/events/details/google-gdg-nagpur-presents-devfest-nagpur-2022/)     (November 5, 2022). Slides are [here](https://bit.ly/nagpur-22). Presented this at [DevFest Tashkent 2022](https://gdg.community.dev/events/details/google-gdg-tashkent-presents-devfest-tashkent-22/) as well. 
- **Improving as an ML Practitioner** at [DevFest Kolkata 2022](https://gdg.community.dev/events/details/google-gdg-kolkata-presents-gdg-devfest-kolkata-2022/) (November 13, 2022). Slides are [here](https://bit.ly/kolkata-22). Presented this at [DevFest Indore 2022](https://gdg.community.dev/events/details/google-gdg-indore-presents-devfest-indore-2022/) as well. 
- **Bringing ML Models to Life with Hugging Face Spaces** at [DevFest Gandhinagar 2022](https://gdg.community.dev/events/details/google-gdg-gandhinagar-presents-devfest-gandhinagar-2022/)  (November 21, 2022). 
- **ML Problems: Formulation and Adoption** at Google Developers Startup Bootcamp (University Edition); Gurugram, India (December 06, 2022). [Tweet](https://twitter.com/GoogleDevsIN/status/1600136189478326273) by GoogleDevsIN. Deck is [here](https://docs.google.com/presentation/d/1owGLGDHMsLEwPta9XigZw3KNXLqlgGIs13PpDjwDek4/edit?usp=sharing). 
- **You Don't Know TensorFlow** at TFUG Kolkata (March 19, 2023). Materials are [here](https://github.com/sayakpaul/you-dont-know-tensorflow/). A recording of the talk can be found [here](https://youtu.be/CjkmHNhzhQg).
- **Open and Collaborative MLOps**, invited lecture at [HKUST](https://hkust.edu.hk/) (March 31, 2023). My slides are [here](https://bit.ly/hf-hkust).
- **Building DALL-E 2 like Systems in Minutes** at [NIT Silchar](https://mlclubnits.com/) (April 8, 2023). Presented on the same topic at [IIT Guwahati](https://www.instagram.com/p/CrS6pCnyvoi/?hl=en) (April 22, 2023). Slides are [here](https://docs.google.com/presentation/u/1/d/16GWo_do9oqD832JkbxEcmPP1ZBDMiQsgoIldlqHSzh0/edit?usp=sharing). 
- **Democratizing Generative Models with 🧨 diffusers** at the [NVIDIA-HF meetup](https://sites.google.com/huggingface.co/generative-ai-meetup) (April 29, 2023) (with Suraj Patil). Slides are [here](https://docs.google.com/presentation/d/1cbcP-wpeb3jMS4-20cEKFmNJAObg13Q_JNbl0YV6qyU/edit?usp=sharing). [Here's](https://docs.google.com/presentation/d/1xJcCUDr7gb18nNLI75r1En1FrdzwaoTPmmAjjVLQodE/edit?usp=sharing) another version of the presentation that I presented at the [DataHack Summit 2023](https://www.analyticsvidhya.com/datahack-summit-2023/current-speaker/sayak-paul/). 
- **Ship Faster TensorFlow Models with XLA** at [Google Cloud Community Days, Kolkata](https://gdgcloud.kolkata.dev/ccd2023/) (May 7, 2023). Slides are [here](https://bit.ly/tensorflow-xla).  
- **Generating Photorealistic Images using AI with Diffusers in Python** at [DataCamp](https://www.datacamp.com/webinars/Generating-photorealistic-images-using-ai-with-diffusers-python) (May 16, 2023). Materials are [here](https://github.com/huggingface/workshops/tree/main/datacamp-webinar). A recording of the session is [here](https://www.youtube.com/live/izFV5hbOXMw?feature=share). 
- **🧨 diffusers for research** at VAL, Indian Institute of Science (IISc) (June 12, 2023). Slides are available [here](https://docs.google.com/presentation/d/1xBfs8yPVC4jeHJR4ShV0YIjpgC6glS4R6xD6BrxaU10/edit?usp=sharing).
- Appeared on a podcast discussing my ML journey and other related things: [Hugging Face's ML Revolution](https://youtu.be/69F-ZpFj2PM).
- **Making Keras Models go brrr with XLA** at [Keras Community Day Kolkata](https://www.townscript.com/e/keras-community-day-kolkata-2023), August 27, 2023. Slides are [here](https://docs.google.com/presentation/d/1mM8LeQDpOOLWsMQffRhuDuPPFx4TL-cV848EZtCN_8k/edit?usp=sharing). I have given the same talk at [Keras Community Day Chandigarh](https://gdg.community.dev/events/details/google-gdg-chandigarh-presents-keras-community-day-chandigarh/) too (September 02, 2023).
- **Bringing SoTA Diffusion Models to the Masses with 🧨 diffusers**, throughout September 2023. Presented this at the following places during my trip to the UK: [The Dyson Robotics Lab](https://www.imperial.ac.uk/dyson-robotics-lab/) at Imperial College of London, Amazon London, and the [Department of Statistics](https://www.stats.ox.ac.uk/) at the University of Oxford. Slides are [here](https://docs.google.com/presentation/d/1y53Own2-934ljJUIu36aFhGDuW0y71Wd6ZxO64-Q-aI/edit?usp=sharing). A recording (Oxford version) is available [here](https://youtu.be/qo5ubQadvfs).
- **Controlling Text-to-Image Diffusion Models**, [BigMAC ICCV Workshop](https://bigmac-vision.github.io/) (October 02, 2023). Slides are [here](https://docs.google.com/presentation/d/1h5m96ne8OHh7mRigMqBTRtiLMADG-r2qudFGL57KCYA/edit#slide=id.p). Recording is [here](https://www.youtube.com/watch?v=XiouM3MEOKs&t=9254s).
- **Bringing SoTA Diffusion Models to the Masses with 🧨 diffusers**, IBM Research (October 17, 2023). Slides are [here](https://docs.google.com/presentation/d/1y53Own2-934ljJUIu36aFhGDuW0y71Wd6ZxO64-Q-aI/edit?usp=sharing). Recording is [here](https://youtu.be/HNXNKPKfCs4).
- **People of AI podcast (Google)**, spoke to Ashley Oldacre and Luiz Gustavo Martins from Google. Episode recording is [here](https://peopleofai.libsyn.com/sayak-paul-getting-started-with-community-contributions-diffusion-models-and-more).
- **End-to-End Pipeline for Segmentation with TFX, GCP, & 🤗** (with Chansung Park), [ML Community Summit 2023](https://x.com/ksoonson/status/1727107370201895233?s=20) (November 23, 2023). Slides are [here](https://docs.google.com/presentation/d/1bnURFQHr98A8NkDhsD5q3WnghIltR1JMONrtLEelQ5A/edit?usp=sharing).
- **Software Engineering Daily**, spoke to Sean Falconer. Podcast recording is [here](https://www.youtube.com/watch?v=Gq80wCzWuKo).
- **Staying relevant as an MLE in the age of GenAI**, DevFest Kolkata 2023 (December 22, 2023). Slides are [here](https://docs.google.com/presentation/d/111mLl9pYS91ApdiBe0p0vsKGeJ33cZm0gBNVDJHKB00/edit?usp=sharing).
- Appeared on the Overpowered podcast with Varun Mayya. Find it [here](https://www.youtube.com/watch?v=IlIhykPDesE).

### Co-organized by me

-   [DevFest Kolkata](http://www.google.com/url?q=http%3A%2F%2Fdevfest.gdgkolkata.org&sa=D&sntz=1&usg=AFQjCNFJA0Xr03VP_q7oWUBG9RweQnHu_w), August 3, 2019.
-   [TensorFlow All-Around Kolkata](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F264055077%2F&sa=D&sntz=1&usg=AFQjCNEDVmgkSk8TwBTH7owjE0usWFzLYg), August 31, 2019.
-   [Let's Build](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F266991860%2F&sa=D&sntz=1&usg=AFQjCNFRNPDLbylmxjuz85soM3VfkJ4YPA), January 4, 2020.
-   [Kolkata Kreate](https://www.google.com/url?q=https%3A%2F%2Fwww.meetup.com%2FGDG-Kolkata%2Fevents%2F268635758%2F&sa=D&sntz=1&usg=AFQjCNEfaOS5hu7zqcZcCOSijr02RZd-Lg), February 29, 2020.
-   [TFUG India Summit](http://tfug.in/), September 3 - 6, 2020.
-   [Generative AI Meet-up](https://sites.google.com/huggingface.co/generative-ai-meetup) in collaboration with NVIDIA, April 29, 2023.
-   [JAX/Diffusers Sprint](https://github.com/huggingface/community-events/edit/main/jax-controlnet-sprint/), March 29 - May 08, 2023. 
-   [Deploying Generative AI Models](https://lu.ma/ijcugt4n) in collaboration with Inferless and Sequoia Capital, June 10, 2023. 

### ML Street Talk

I used to appear on one of the most popular podcasts in machine learning called the [ML Street Talk](https://www.youtube.com/channel/UCMLtBahI5DMrt0NPvDSoIRQ). Below are the episodes where I have made  appearances. 

-   [Spoke](https://bit.ly/ml-st-sayak) to Tim Scarfe, Connor Shorten, and Yannic Kilcher.
-   [Spoke](http://bit.ly/mlst-mathilde) to **Mathilde Caron** (Research Assistant at Facebook AI), with Ayush Thakur, Tim Scarfe, and Yannic Kilcher.
-   [Spoke](http://bit.ly/sara_mlst) to **Sara Hooker** (Google Brain), with Tim Scarfe, and Yannic Kilcher.
-   [Spoke](http://bit.ly/sanyam_mlst) to **Sanyam Bhutani** (H2O.ai), with Tim Scarfe, Yannic Kilcher, and Alex Stenlake.
-   [Spoke](https://youtu.be/1EqJyMy0LnE) to **Simon Kornblith** (Google Brain) with Tim Scarfe and Yannic Kilcher.
-   [Spoke](https://youtu.be/Q0kN_ZHHDQY) to **Lena Voita** (University of Edinburgh and University of Amsterdam) with Tim Scarfe and Yannic Kilcher.
-   [Spoke](https://www.youtube.com/watch?v=_eHRICHlg1k) to **Hadi Salman** (MIT) with Tim Scarfe and Yannic Kilcher.
-   [Spoke](https://www.youtube.com/watch?v=EXJmodhu4_4) to **Ishan Misra** (Facebook AI Research) with Tim Scarfe and Yannic Kilcher.

**Note:** If you are interested to invite me as a speaker for your event, please get in touch by dropping an email at [spsayakpaul@gmail.com](mailto:spsayakpaul@gmail.com). If you are interested in having me submit a CFP first, that is absolutely fine! Please don't hesitate to ask that.
