---
title: "Talks"
aliases:
  - /talks
toc: false
---

Talks, workshops, podcasts, and recordings.

### Abhishek Thakur' Podcast - GenAI Engineer's Journey

<iframe width="560" height="315" src="https://www.youtube.com/embed/m3FZPsDo2vw?si=gq7v26RZV78OP8xM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

### YouTube - Building with AI

<iframe width="560" height="315" src="https://www.youtube.com/embed/2Xo11kjJiZk?si=8WjEXpvuFG8jRfmx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

### Data Hack Summit - Demystify Parallel Programming: Hands-on with CUDA for GenAI

I gave [this talk](https://www.analyticsvidhya.com/datahacksummit-2024/sessions/demystify-parallel-programming-hands-on-with-cuda-for-genai) at Data Hack Summit by Analytics Vidhya. It covered CUDA C fundamentals and core CUDA concepts like threads, blocks, and memory hierarchies. The session guided attendees through writing their first CUDA kernels, aiming to build the skills needed to optimize deep learning workloads.


---

*I gave a lot of talks travelling across 11 cities throughout India after finishing my Google Summer of Code.*



1. [KerasNLP: From Words to Wisdom](https://twitter.com/gdg_nd/status/1709132486238724550?t=9V1JG6XwqQNJz6MEuiGqPA&s=08), on October 7, 2023 at DevFest New Delhi'23.

2. [Modular NLP Workflows with KerasNLP](https://x.com/margaretmz/status/1706717545007546491?s=20), on September 29, 2023 at Google Developer Groups, Seattle.

3. [Supercharging Keras with WandB](https://twitter.com/tfugmumbai/status/1705456979756613978?s=20), on September 23, 2023 at TensorFlow User Group Mumbai.

4. [GSoC Success Secrets: Cracking the Code to OSS Excellence](https://www.linkedin.com/feed/update/urn:li:activity:7105945831630938112/), September 10, 2023 at National Institute of Technology, Warangal.

5. [Rethinking LLM Design with KerasNLP](https://twitter.com/kanpuriyanawab/status/1694540731783028926?s=20), on August 26, 2023 at TensorFlow User Group Hyderabad.

6. [KerasNLP for Starters](https://www.youtube.com/watch?v=KinLN4lA6Bg&t=3450s), on August 20, 2023 at TensorFlow User Group Durg

7. [Taking KerasNLP on GenAI Ride]() on July, 23, 2023 at TensorFlow User Group, Kolkata

8. [Re-imagining Keras in the evolving ML ecosystem](https://www.linkedin.com/posts/kanpuriyanawab_event-developercommunity-congratulations-activity-7086588533510934528-dS2y) on July 16, 2023 at Google I/O Extended'23 New Delhi.
