---
title: "XYZ"
aliases: 
  - /xyz
toc: false
---

On this page, I have listed some things that I do/used to do in the pursuit of "happyness".

### Misc

-   Taught under-privileged children and managed operations for a TCS-CSR initiative called H20 (Helping Hand Organization) (2017)
-   [Moderator](https://drive.google.com/file/d/1gezVW0yIzT6fyJXpY1Lp8MRk_3KjkpSt/view?usp=sharing) of the Artificial Intelligence channel of [Campus Commune](https://www.google.com/url?q=https%3A%2F%2Fcampuscommune.tcs.com%2Fintro&sa=D&sntz=1&usg=AFQjCNE5PHqA0UZ94F9-J1g45TeQrWaDqQ) (Jan, 2018 - August, 2018)
-   Book reviewer for [Manning Publications Co](https://www.google.com/url?q=https%3A%2F%2Fmanning.com&sa=D&sntz=1&usg=AFQjCNEc5srwZ30NHgmLXaLpiOqgjBMOHw) (2019 - 2022)
-   Co-organizer of [GDG Kolkata](https://www.meetup.com/GDG-Kolkata/) (2019 - 2021)
-   Organizer of [TensorFlow User Group Kolkata](https://tfugkol.github.io/) (2020 - 2021)

### Mentorship

- [Launchpad Women Entrepreneurs](https://photos.app.goo.gl/TGoyxJRz6sDrY91x7) (2019)
- [Explore ML Academy, Hyderabad](https://events.withgoogle.com/explore-ml-in/) (2019)
- [AI Hack Tunisia](https://www.google.com/url?q=https%3A%2F%2Fwww.ai-hack-tunisia.com&sa=D&sntz=1&usg=AFQjCNHR8mJv6TwI1_Jmfss0xaG8ivBlJg) (2019)
- [Class III (2019) of Launchpad Accelerator India](https://india.googleblog.com/2019/08/inviting-applications-for-class-3-of.html)  ([Tweet](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN%2Fstatus%2F1184417773457309696&sa=D&sntz=1&usg=AFQjCNGNkB4cfH6TAYH8r01D2BtpeyozJA) by [GoogleDevsIN](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN&sa=D&sntz=1&usg=AFQjCNF2cyw8Wvt0ANu9OK_AC-LPZcY2Ww))
- [Google Code-in](https://codein.withgoogle.com/) for TensorFlow through December, 2019 - January 2020 ([Certificate](https://drive.google.com/file/d/1DcTS7ogACmuvnvGJWw5-3yL9xp06IJPc/view?usp=sharing))
- [Build For Digital India](https://events.withgoogle.com/buildfordigitalindia/) Bootcamps through January 2020 - February 2020 ([Tweet](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN%2Fstatus%2F1225747137616498690&sa=D&sntz=1&usg=AFQjCNHOArwPGTqTx17LLJvq9KHI_KQueA) by [GoogleDevsIN](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN&sa=D&sntz=1&usg=AFQjCNF2cyw8Wvt0ANu9OK_AC-LPZcY2Ww))
- [Explore ML Bootcamp, Hyderabad (2020)](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN%2Fstatus%2F1230456116158418944&sa=D&sntz=1&usg=AFQjCNGBh7XuMdRHv0vtDM-KZNgIgGpKdg)  ([Tweet](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN%2Fstatus%2F1230456116158418944&sa=D&sntz=1&usg=AFQjCNGBh7XuMdRHv0vtDM-KZNgIgGpKdg) by [GoogleDevsIN](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FGoogleDevsIN&sa=D&sntz=1&usg=AFQjCNF2cyw8Wvt0ANu9OK_AC-LPZcY2Ww))
- [Google for Startups MENA Accelerator 2020](https://startup.google.com/accelerator/middle-east-north-africa/) (this was formerly known as Launchpad)
- [Google for Startups India Accelerator 2020, 2021](https://twitter.com/GoogleDevsIN/status/1302932126019411970) 
- Mentored for TensorFlow at [Google Summer of Code 2021 (GSoC)](https://summerofcode.withgoogle.com/). Students: [Aditya Kane](https://github.com/AdityaKane2001/regnety) and [Vasudev Gupta](https://github.com/vasudevgupta7/gsoc-wav2vec2). [Here's](https://blog.tensorflow.org/2021/09/tensorflow-hubs-experience-with-gsoc-2021.html) a related blog post from TensorFlow.
- [Deep Learning Indaba](https://deeplearningindaba.com/). Various university students from Africa since the mentorship program is Africa-focused (2021- 2022).
- Mentored for TensorFlow at GSoC 2022. Students: [Aditya Kane](https://adityakane2001.github.io/opensource/gsoc2022report), [Sayan Nath](https://sayannath.github.io/MobileViT-GSoC/), and [Mohammad Shoaib](https://github.com/shoaib6174/GSOC-22-Video-Swin-Transformers/blob/main/assets/final_report.md). My mentorship certificate is [here](https://drive.google.com/file/d/1300UqW59N98d5No_LYhGAWdBaPVQwyfc/view?usp=share_link).
- [Google for Startups India Women Founders Accelerator (2022)](https://rsvp.withgoogle.com/events/google-for-startups-accelerator-india-women-founders/home).
- Mentored at [KaggleX BIPOC 2023](https://www.kaggle.com/kagglex-bipoc-mentorship-program). [Here](https://drive.google.com/file/d/1QicXwcU4g9VUX290yvjg-VqHDh-fQ8xe/view?usp=share_link) is my certificate.

Apart from the occasions mentioned above, I have mentored individual students, students belonging to [Google Developer Student Clubs]((https://gdsc.community.dev/)), etc. But I don't have any recorded documents for these. I enjoy sharing my learnings with those in need and, in turn, learning from them.

### Awards and recognition

-   Recipient of the **Google Open Source Peer Bonus Award** ([2020](https://opensource.googleblog.com/2020/10/announcing-latest-google-open-source.html), [2021](https://opensource.googleblog.com/2021/09/announcing-latest-open-source-peer-bonus-winners.html), and [2022](https://opensource.googleblog.com/2022/09/announcing-the-second-group-of-open-source-peer-bonus-winners-in-2022.html)). [Here's a related blog post](https://opensource.googleblog.com/2020/10/peer-bonus-experiences-building-tiny.html) (from the official Google Open Source Blog) jotting down the experiences that led to this honor (2020).
-   Led our team at PyImageSearch to Top 10 at [this CVPR 2021 competition](https://competitions.codalab.org/competitions/28113). 
-   Finished 2nd (with [Siddha Ganju](https://sidgan.github.io/siddhaganju)) at [this competition](https://nasa-impact.github.io/etci2021/) (2021) organized by the NASA Impact team ([Certificate](https://drive.google.com/file/d/1U4JTAYChV6PHwDA87gd2FJ04843YA6bN/view?usp=sharing)).
-   Received (sometimes jointly) the [#TFCommunitySpotlight award](https://blog.tensorflow.org/2020/11/tensorflow-community-spotlight-program-update.html) multiple times for projects with varying use-cases, tooling, and motivation. Details in the
    following tweets by TensorFlow: [Tweet 1](https://twitter.com/TensorFlow/status/1351590466068783105), [Tweet 2](https://twitter.com/TensorFlow/status/1428433434972618754), [Tweet 3](https://twitter.com/TensorFlow/status/1446611368078086144?s=20), [Tweet 4](https://twitter.com/TensorFlow/status/1460321709488152579), [Tweet 5](https://twitter.com/TensorFlow/status/1469019016782041095?s=20), [Tweet 6](https://twitter.com/TensorFlow/status/1516869315517198337), [Tweet 7](https://twitter.com/TensorFlow/status/1521558632768409600), [Tweet 8](https://twitter.com/TensorFlow/status/1540033393462738944), [Tweet 9](https://twitter.com/TensorFlow/status/1545115276152389636), [Tweet 10](https://twitter.com/TensorFlow/status/1611469033714470919?s=20&t=a5LMpYXrPg6E0WGudsYezw), and [Tweet 11](https://twitter.com/TensorFlow/status/1626629821022208020).
-   Ranked 8 at [Applied Roots Blogathon 2021](https://drive.google.com/file/d/11j3gJSaaCtu-Gq4ziKbG0RMBvXecha45/view?usp=sharing).
-   Recipient of the [Intel Top Innovator Award (2019)](https://www.dropbox.com/s/mzsy1q8jgkwj6cj/Intel_Top_Innovator_2019.jpg?dl=0).
-   Became a [Google Cloud Innovator (Champion tier)](https://cloud.google.com/innovators/innovator?profileId=114302939543313329085).
-   Awarded as the **Top Regional Contributor** from India for TensorFlow, 2021. [Blog post](https://blog.tensorflow.org/2021/11/2021-TF-Contributor-Awardees.html?linkId=8010214) and [Tweet](https://twitter.com/TensorFlow/status/1465369133873250307?s=20) from TensorFlow.
-   Received [NeurIPS 2021 AI4Science Workshop Travel Grant](https://ai4sciencecommunity.github.io/) for [this
    work](https://openreview.net/forum?id=kXgbFvXcwDX). 
-   Received the [Google OSS Expert Prize (February, 2022)](https://www.kaggle.com/general/310354) with [Soumik Rakshit](https://www.kaggle.com/soumikrakshit) for [this work](https://www.kaggle.com/soumikrakshit/gaugan-keras/). 
-   Received the [Google OSS Expert Prize (March, 2022)](https://www.kaggle.com/general/316181) with [Aritra Roy Gosthipaty](https://www.kaggle.com/aritrag) for [this work](https://www.kaggle.com/code/spsayakpaul/mae-keras). 
-   Received the [Google OSS Expert Prize (April, 2022)](https://www.kaggle.com/discussions/general/322041) for [this work](https://www.kaggle.com/code/spsayakpaul/distilling-vision-transformers). 
-   Received the [Google OSS Expert Prize (May, 2022)](https://www.kaggle.com/discussions/general/328914) with [Aritra Roy Gosthipaty](https://www.kaggle.com/aritrag) for [this work](https://www.kaggle.com/code/aritrag/probing-vits). 
-   Awarded as a Top Contributor to [Papers With Code](https://paperswithcode.com/). Award link is [here](https://github.com/sayakpaul/portfolio/blob/master/images/pwc_award.jpg).
-   Accepted to the [Oxford ML Summer School (2022)](https://www.oxfordml.school/) for the healthcare track. Certificate link is [here](https://drive.google.com/file/d/14DKioe8HRjKkXEeRXAhmclqUP8cvv9Z0/view?usp=sharing).
-   Received the [Kaggle ML Research Spotlight Prize (September, 2022)](https://www.kaggle.com/discussions/general/358450) for [this work](https://www.kaggle.com/code/spsayakpaul/cait-tf). 
-   Received the [Kaggle ML Research Spotlight Prize (November, 2022)](https://www.kaggle.com/discussions/general/370095) for [this work](https://www.kaggle.com/code/spsayakpaul/robustness-vit/notebook). 
-   [Secured 2nd place](https://discuss.tensorflow.org/t/announcing-the-keras-community-prize-first-edition/13148/29) in the first ever Keras Community Prize Competition organized by Google for [this project](https://github.com/sayakpaul/stable-diffusion-keras-ft) with [Chansung Park](https://twitter.com/algo_diver). 

### Non-tech

- I love listening to all genres of music. A guitar player myself. Have played in a band  [**Behest**](https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2Fbehestmusic%2F%3Fref%3Dbr_rs&sa=D&sntz=1&usg=AFQjCNGVtpjfBDP7p17lrvefzoNuoXDg9w)  from 2013 to 2017. 
- I love watching TV serials also (Narcos, Suits, Downton Abbey, Breaking Bad, Ozark being all-time favorites). 
